n_components_list: # targets dimension list
  - 18211
d_models_list:
  - 128
batch_size: 32
data_file: 'de_train.parquet'
id_map_file: 'id_map.csv'
device: cuda
seed: null
models_dir: 'trained_models_non_k_means_mean'
mean_std: "mean" #mean or mean_std
